# Generated by Django 3.0.6 on 2020-06-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SKU',
            new_name='sku',
        ),
    ]
