# Generated by Django 3.0.6 on 2020-06-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200607_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ratings',
            new_name='rating',
        ),
    ]
