# Generated by Django 3.0.6 on 2020-06-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_has_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_size',
            new_name='has_sizes',
        ),
    ]
